### PR TITLE
refactor: remove packages/angular

### PR DESCRIPTION
**Pull request by alexeagle**
It is moving to https://github.com/just-jeb/angular-builders/pull/1048

We announced the deprecation in the README of this package for 4.x

### CODE REVIEW

**Comment by jbedard** [comment]
Should we add a link to that project? Or just as part of the 5.0 changelog?

**Comment by alexeagle** [comment]
@jbedard where are you suggesting that link would go? it's already on https://www.npmjs.com/package/@bazel/angular in the README for anyone prior to the next release to see

**Comment by jbedard** [comment]
I guess I was thinking in a changelog? Although I don't see any other reference to this project in the changelog so 🤷

**Comment by alexeagle** [comment]
Looking for an approve from you so I can merge 

Will def be in the 5.0 release notes

**Review by jbedard — APPROVED** [review]

**Pull request merged**
