### PR TITLE
fix: yarn cache path should be a string

### PR DESCRIPTION
**Pull request by siddharthab**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue: #1678

## Does this PR introduce a breaking change?

- [] Yes
- [x] No

### CODE REVIEW

**Comment by gregmagolan** [comment]
Fixes #1678

**Comment by siddharthab** [comment]
Thank you for the quick merge. Do you have guidance on when this change will be in a release? Or can I use the commit hash directly?

**Comment by alexeagle** [comment]
We don't publish release snapshots yet, and the layout of the source repo doesn't match what we publish (has a bunch of development dependencies for example) so the easy way to pull this into your project is to patch it, see https://github.com/bazelbuild/rules_nodejs/blob/master/docs/index.md#patching-the-built-in-release

**Comment by siddharthab** [comment]
Thanks! A patch file should work just fine.

**Pull request merged**
