### PR TITLE
test: fix and enable e2e smoke test

### PR DESCRIPTION
**Pull request by jbedard**

### CODE REVIEW

**Review by alexeagle — COMMENTED** [review]
it's still red though?

I wonder if we can get rid of the integration_test runner setup here. Either something akin to what we do in other rulesets on GitHub actions, or something built-in to bazelci?

Or maybe we should use bazel-contrib/bazel-integration-test

**Comment by jbedard** [comment]
Sorry I should have left this as a draft for now. Still some errors that I need CI to test.

**Comment by jbedard** [comment]
I'll look into bazel-contrib/bazel-integration-test though, the more we can delete the better 👍

**Comment by alexeagle** [comment]
Oh gross, Windows failing :(

**Comment by jbedard** [comment]
Going to just jump to the deletion instead... https://github.com/bazelbuild/rules_nodejs/pull/3655

**Pull request closed without merging**
