### PR TITLE
Add spica to adopter organization list

### PR DESCRIPTION
**Pull request by thesayyn**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ X ] Other... Please describe: Add spica to adopters

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by mattem — APPROVED** [review]
Awesome, thanks! 🚀

**Comment by mattem** [comment]
Oh I missed that this targeted master, 2 secs...

**Comment by thesayyn** [comment]
it happens. 😄 I have deleted the branch though. Should I create a new one against the stable branch?

**Comment by mattem** [comment]
I cherry-picked the change over to #2184, I think it just needs a `@googlebot I consent.` from you for the CLAs

**Comment by thesayyn** [comment]
@googlebot I consent.

**Pull request merged**
