### PR TITLE
Update nodejs versions

### PR DESCRIPTION
**Pull request by mattinsler**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe:

Ran the update-nodejs-versions script and committed the changes.

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by mattem** [comment]
Thanks for the PR. I'm hesitant to include the addition of NodeJS 15.0.0+ currently as it ships with npm7, which currently is causing failing tests in https://github.com/bazelbuild/rules_nodejs/pull/2268 so we are unable to validate the compatibility with rules_nodesjs.

Perhaps we could separate out the other versions for the moment?

**Comment by sharmilajesupaul** [comment]
@mattem @mattinsler could land latest 10, 12, & 14 only in this PR? it'll help unblock implementations using these versions.

**Comment by mattinsler** [comment]
I'll add a max version constant to the script so we can make this change when support is added for 15+. I'd like this to be automatic so that #2285 can land next.

**Review by mattem — APPROVED** [review]

**Comment by mattem** [comment]
Thanks! 🚀

**Pull request merged**
