### PR TITLE
Fix copy_file on Windows

### PR DESCRIPTION
**Pull request by cocreature**
In general you cannot rely on mkdir and cp being in path here and this
below up for us on CI. Given that this is a repository rule you also
cannot rely on something like rules_posix to resolve them otherwise so
this PR hacks around this in a rather crude but working way.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

rules_nodejs fails on Windows if msys mkdir or cp are not in path.

## What is the new behavior?

No dependency on msys.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]
Thanks! The logic is isolated enough I'm not too worried about hackiness

**Comment by cocreature** [comment]
Hm something seems off with the copy stuff on CI. Interestingly we did not hit this on our own CI.

**Comment by alexeagle** [comment]
Can you reproduce locally on windows?
I don't want Bazel team to yell at us about CI utilization

**Comment by mattem** [comment]
Isn't it expected that the user has installed MSYS2 (as per the bazel windows setup, https://docs.bazel.build/versions/master/install-windows.html#installing-compilers-and-language-runtimes) and these utilities are on the PATH? This is why CI doesn't have issues here.

**Comment by cocreature** [comment]
Alright I think I got it to work now. Sorry again for the noise and CI usage. The fix was to switch from `copy` to `xcopy`. `copy` uses `+` to represent file appends and there doesn’t seem to be a great way to escape this without breaking other things.

**Pull request merged**
