### PR TITLE
feat(@bazel/typescript): allow typescript 4.4 in dep

### PR DESCRIPTION
**Pull request by longlho**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by alexeagle** [comment]
I added a commit to test the upgrade, and TS 4.4 seems to break the custom TS compiler in the ts_library rule :(

**Comment by longlho** [comment]
hmm let me see if I can fix that

**Comment by alexeagle** [comment]
@devversion any chance you have time to get this angular example upgrade working so we can use TS 4.4?

**Comment by devversion** [comment]
@alexeagle hey, yeah. I can try having a look over the holidays!

It's a little unclear to me what the canonical Bazel example should look like. As of v13, either apps would need to create UMD bundles for Angular NPM packages on their own, or use a bundled like esbuild for tests, dev-app etc. In Angular/components we combine both but that is pretty advanced. I'm leaning towards the esbuild approach as code is already bundled in the example as it seems.

Just throwing this out in case you have any strong feelings

**Comment by lencioni** [comment]
https://github.com/bazelbuild/rules_nodejs/pull/3191

**Comment by alexeagle** [comment]
I think it's essentially fixed by #3191 since `@bazel/typescript` has the wider peer dep.
The rest of this change is still stuck :(

**Pull request closed without merging**
