### PR TITLE
feat(examples): upgrade rules_docker to 0.13.0

### PR DESCRIPTION
**Pull request by Toxicable**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by Toxicable** [comment]
One failure is due to 
```
2019/12/21 05:23:32 Image pull was unsuccessful: reading image "gcr.io/google-appengine/debian9@sha256:c05b781371f75d1bd7a199bc83de177173cc80c98dbfb6c1ef7075757addece4": .dockercfg: $HOME is not defined
```
In CircleCI, It looks like rules_docker is looking for `$HOME/.dockercfg` but failing due to `$HOME` not being defined.
What docker container are these run in, could we adjust it to get $HOME defined?
Or should we push back at rules_docker to not look for this file if `$HOME` isn't defined?

**Comment by alexeagle** [comment]
I don't know whether it's correct for rules_docker to look for `$HOME` 
but it looks like we just need to provide a value for `docker_client_config` so it doesn't try to look there?

**Comment by Toxicable** [comment]
So if I try work around it by defining HOME just for that command I get this failure 
https://circleci.com/gh/bazelbuild/rules_nodejs/37598?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Is there some other way we could work around this for now?

**Comment by Toxicable** [comment]
not really sure how to proceed with this one, is there somewhere we could just define `HOME` in our environment to work around the above issue?

**Comment by alexeagle** [comment]
I tried a couple of things, looks like just having the integration test runner define a `$HOME` env variable is sufficient.
added to the commit

**Comment by alexeagle** [comment]
Currently stuck because the environment for a bazel-in-bazel is missing something that git needs to do operations...

**Comment by alexeagle** [comment]
I confirmed that it passes with `SSH_AUTH_SOCK=/tmp/circleci-090238626/ssh_auth_sock` so need to plumb that through

**Comment by gregmagolan** [comment]
@googlebot I consent.

**Pull request merged**
