### PR TITLE
fix: allow cypress to run on m1 macs

### PR DESCRIPTION
**Pull request by CooperBills**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Bazel fails to run Cypress tests with an M1 Mac (Darwin arm64) host, as it is unable to find a toolchain that doesn't limit the host to an x86 CPU.

Issue Number: https://github.com/bazelbuild/rules_nodejs/issues/3085

## What is the new behavior?
The CPU architecture compatibility restriction is removed in this PR, so Cypress will run using the x86 build under rosetta (note: Cypress' [official take](https://www.cypress.io/blog/2021/01/20/running-cypress-on-the-apple-m1-silicon-arm-architecture-using-rosetta-2/) is: "the way to run Cypress on Apple M1 ARM chip is by using Intel emulation with Rosetta 2, Apple's translation layer."). As of opening this PR, Cypress still does not have a native arm64 build.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

Discussion/Questions:
* Is this fine, or should we be defining a separate toolchain_config for `darwin_arm64` with another appropriately named toolchain and `@cypress_*`external which really just pulls the x86 build again under the hood?
* Should we add any documentation stating that rosetta is required on the host? (it's very likely that any mac developer will already have it installed)

### CODE REVIEW

**Comment by alexeagle** [comment]
> defining a separate toolchain_config for darwin_arm64 with another appropriately named toolchain and @cypress_*external which really just pulls the x86 build again under the hood

I think this is probably better, since it gives us the ability to warn about rosetta, and when/if they do release M1 binaries, it's a smaller change to modify that toolchain_config than to introduce a new one at that time.

Note that I'm hoping to spin out cypress to its own repository so that it could have independent maintainers, but probably not happening before 5.x.

Thanks!

**Review by alexeagle — APPROVED** [review]
Thanks!

this toolchain needs some cleanup to avoid eager-evaluation of the RHS of the `select()` statement. I think right now it will download for all platforms? Maybe even an extra download since you have another `http_archive` here now.

**Comment by CooperBills** [comment]
Yeah, I'm pretty sure it will end up downloading another archive... Is that acceptable or would you like me to take a look at lazy-loading the cypress toolchains before merging this? Do you know of documentation or a good example I could look at for lazy evaluation of select statements for toolchains? (Only thing I could find was rules_rust's "proxy repositories": https://github.com/bazelbuild/rules_rust/blob/main/rust/repositories.bzl#L263-L264)

**Comment by alexeagle** [comment]
https://github.com/aspect-build/bazel_rules_template/blob/main/mylang/private/toolchains_repo.bzl has some docs about that.

Pretty sure @mrmeku will make a new cypress rule from that template sometime soon, and we'll port over any fixes from here. So I think this is good to merge. Thanks!

**Pull request merged**
