### PR TITLE
Update esbuild versions

### PR DESCRIPTION
**Pull request by mattem**
- Updated esbuild versions using `yarn run update-esbuild-versions`

Auto-generated by [create-pull-request][1]

[1]: https://github.com/peter-evans/create-pull-request

### CODE REVIEW

**Comment by mattem** [comment]
This missed the lock file changes 😕

**Review by alexeagle — APPROVED** [review]

**Comment by alexeagle** [comment]
@mattem looks like a real CI failure
```




npm ERR!
  | npm ERR!
  | npm ERR! Invalid: lock file's esbuild@0.12.21 does not satisfy esbuild@0.12.25
  | npm ERR!
  |  
  | npm ERR! A complete log of this run can be found in:
  | npm ERR!     /var/lib/buildkite-agent/.npm/_logs/2021-09-03T02_20_31_434Z-debug.log
  | )
  | ERROR: Analysis of target '//src:bundle' failed; build aborted: Analysis failed
 
```

**Comment by mattem** [comment]
Yeah, the action didn't add and commit the lock file changes made by the script. Perhaps some config needs tweaking.

**Comment by mattem** [comment]
Opps, https://github.com/bazelbuild/rules_nodejs/pull/2922

**Pull request closed without merging**
