### PR TITLE
chore: update architect example to Angular 10

### PR DESCRIPTION
**Pull request by alexeagle**

### CODE REVIEW

**Comment by alexeagle** [comment]
```
❯ Update Browserslist configuration file name to '.browserslistrc' from deprecated 'browserslist'.
✖ Migration failed: ENOENT: no such file or directory, rename '/Users/alex.eagle/Projects/rules_nodejs/examples/angular_bazel_architect/dist/angular_bazel_architect/bazel-out/darwin-fastbuild/bin/e2e.sh.runfiles/angular_bazel_architect/browserslist' -> '/Users/alex.eagle/Projects/rules_nodejs/examples/angular_bazel_architect/dist/angular_bazel_architect/bazel-out/darwin-fastbuild/bin/e2e.sh.runfiles/angular_bazel_architect/.browserslistrc'
  See "/private/var/folders/r7/2kp53v7n091gcz93xlt7wtd80000gn/T/ng-KFpD3Q/angular-errors.log" for further details.
```

Do you think the migrations do something I actually need to have in the example, or is that just a best-practice?

**Comment by alan-agius4** [comment]
Mostly best practices

**Comment by alan-agius4** [comment]
If you remove the `bazel-out` link the migration should run successfully.

**Comment by alan-agius4** [comment]
If you want you can get this in and I’ll try to run the migrations sometime this week.

**Comment by alexeagle** [comment]
Thanks I was in a hurry and not reading the error very closely :)
ng update does all the right things of course, it's well-done as always 🌹

**Comment by alexeagle** [comment]
(note, this appears as mergeable because we need to add branch protections to `stable` - I'll still wait for an approve here as usual)

**Pull request merged**
