### PR TITLE
Fix in npm fine grained deps for files or folders that start with '@'

### PR DESCRIPTION
**Pull request by gregmagolan**
Issue came up when downstreaming to material2 which depends on the `scss-bundle` npm package that has files under the folder `@types/*`

### CODE REVIEW

**Comment by gregmagolan** [comment]
The `:` prefix is needed for files that start with `@` so bazel doesn't get confused thinking that you are referring to a workspace:

```
filegroup(
    name = "scss-bundle__files",
    srcs = [
        ":.github/ISSUE_TEMPLATE/Bug_report.md",
        ":.github/ISSUE_TEMPLATE/Feature_request.md",
        ":@types/arguments.d.ts",
        ":@types/bundle-cli.d.ts",
        ":@types/bundler.d.ts",
        ":@types/contracts.d.ts",
        ":@types/helpers.d.ts",
        ":@types/index.d.ts",
        ":@types/launcher.d.ts",
```

**Comment by alexeagle** [comment]
The diff is huge because `scss-bundle` has so many transitive deps. Maybe just add a file to `@gregmagolan/test-a` that tickles the bug?

**Comment by gregmagolan** [comment]
> The diff is huge because `scss-bundle` has so many transitive deps. Maybe just add a file to `@gregmagolan/test-a` that tickles the bug?

Sounds good

**Comment by gregmagolan** [comment]
Added a `@bin/test.js` file to `@gregmagolan/test-a@0.0.4`: 

```
filegroup(
    name = "test-a__files",
    srcs = [
        ":@bin/test.js",
        ":main.js",
        ":package.json",
```

for testing the fix

**Pull request merged**
