### PR TITLE
fix(typescript): propagate tags to validate_options

### PR DESCRIPTION
**Pull request by djmarcin**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #3259 

## What is the new behavior?
Tags are propagated to the validate_options rule

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

Strictly, the answer here might be yes, particularly if someone was doing something very esoteric with custom tags and relying on the fact that propagation to this rule was not happening, but this seems extremely unlikely.

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]
Thanks!

Do you think we might want `testonly` and `visibility` to be propagated as well? Just thinking to be consistent with https://github.com/bazelbuild/rules_nodejs/blob/5.x/packages/typescript/index.bzl#L507-L511

**Comment by djmarcin** [comment]
> Thanks!
> 
> Do you think we might want `testonly` and `visibility` to be propagated as well? Just thinking to be consistent with https://github.com/bazelbuild/rules_nodejs/blob/5.x/packages/typescript/index.bzl#L507-L511

Seems reasonable. The target is named with a leading underscore (`_validate...`) so it seems like it's not intended to be depended on by other things, making testonly and visibility likely extraneous but it probably doesn't hurt.

**Comment by djmarcin** [comment]
@alexeagle I moved `common_kwargs` up and reused it for `validate_options`. It seems like this may also be good to pass to [write_tsconfig](https://github.com/bazelbuild/rules_nodejs/blob/9bc681d14ba197752e4770d95bfc524825d6082f/packages/typescript/internal/ts_project.bzl#L725-L731) and [nodejs_binary](https://github.com/bazelbuild/rules_nodejs/blob/9bc681d14ba197752e4770d95bfc524825d6082f/packages/typescript/internal/ts_project.bzl#L762-L787), but I did not do that here as it expands the scope of the PR a bit. The `write_tsconfig` macro needs to be further modified to take & pass along **kwargs to the underlying rule. Let me know if I should add that here.

**Review by alexeagle — APPROVED** [review]

**Comment by alexeagle** [comment]
buildifier failed - I'd suggest running `pre-commit install` in this repo so a git pre-commit hook will always format your starlark.

**Comment by djmarcin** [comment]
> buildifier failed - I'd suggest running `pre-commit install` in this repo so a git pre-commit hook will always format your starlark.

fixed & force pushed the last commit (not sure what the convention for this repo is in terms of the structured commit messages and trivial typo fixes like that...)

**Pull request merged**
