### PR TITLE
add .umd.js.map files to Ng Apf files

### PR DESCRIPTION
**Pull request by Toxicable**
## PR Checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?
- [x] Feature (please, look at the "Scope of the project" section in the README.md file)

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information
fixes https://github.com/bazelbuild/rules_nodejs/issues/764#issuecomment-492902720

### CODE REVIEW

**Comment by gregmagolan** [comment]
Oh, right. That's doesn't work because the map files end up in the ts_devserver bundle via scripts but actually need to be in data. Thanks for putting this up.

@Toxicable Does adding the maps manually to `data` get you the stack traces you expect?

They should make it there automatically but the question is what is the cleanest path?
1) adds a `scripts_maps` the NodeModuleSources provider and have those picked up by `sources_aspect` into `dev_maps`
2) makes `scripts` in NodeModuleSources both .js & the .map files and have `sources_aspect` put `.js` files into `dev_scripts` and `.map` files into `dev_maps`
3) makes `scripts` in NodeModuleSources both .js & the .map & `dev_scripts` have both & have ts_devserver & ts_web_test_suite sort between .js & .map files in `dev_scripts`

(1) seems least desirable since `sources` in NodeModuleSources is already a mixed bag of files so no reason that `scripts` can be both .js files and .map so I think it's probably either (2) or (3)

Thought?

/cc @alexeagle @kyliau

**Comment by alexeagle** [comment]
We need a failing test that demonstrates a broken source map. Somehow we need a node program that looks like the actual client, and uses source-map-support to assert that the stack traces map back to the right .ts lines

**Comment by Toxicable** [comment]
I started on a PR which would act like a editor to check the paths produced by source maps
https://github.com/bazelbuild/rules_nodejs/pull/722

This could be extended to include colunm and line checks

**Comment by alexeagle** [comment]
@Toxicable could you re-base on https://github.com/bazelbuild/rules_nodejs/pull/848 and fix the test?

**Comment by gregmagolan** [comment]
> @Toxicable could you re-base on #848 and fix the test?

#848 merged :)

**Comment by Toxicable** [comment]
@gregmagolan @alexeagle  Done

**Comment by Toxicable** [comment]
CI failing due to:
>12 06 2019 19:23:14.661:WARN [middleware:karma]: Invalid file type (map), defaulting to js.

Looks like something is picking up the map files, and trying to test them

**Comment by Toxicable** [comment]
probably needs to be rewritten with the changes to `generate_build_file.js`, will do if there's interest in the related ticket

**Pull request closed without merging**
