### PR TITLE
Add mocha_node_test rule

### LINKED ISSUE #168: Add mocha_test rule
Similar to jasmine_node_test, create a mocha wrapper for running simple TS / javascript / node unit tests.

Other similar nodejs rulesets for bazel already support this: https://github.com/pubref/rules_node#mocha_test

### PR DESCRIPTION
**Pull request by pscarey**
Resolves #168 

- Runs NodeJs tests using the mocha test runner.
- Supports mocha.opts and additional arguments to mocha.
- Rule tests included.
- Happy to add documentation (if wanted) to the Readme.

### CODE REVIEW

**Comment by pscarey** [comment]
Documentation has been added.

Let me know if anything further is required from me.

Once this is done I can follow up with a mocha_ts_node_test in the rules_typescript repo.

**Comment by alexeagle** [comment]
Hey, thanks for the hard work, but I have some sad news, there was already https://github.com/bazelbuild/rules_nodejs/pull/308 open. I'm sure there are some bits you've done better, which we ought to incorporate into that PR. Alternately we could land that one first and then you can re-base your improvements on top. What would you like to do?

Also, `mocha_node_test` should work automatically with compile-to-JS language inputs, users shouldn't have to distinguish by writing anything different in their BUILD files.

**Comment by pscarey** [comment]
No issue. I only saw the other Pull Request after submitting. Only interest is in testing our code & helping out if I can. Will continue discussion on issue #168.

**Comment by alexeagle** [comment]
Closing since this is quite out-of-date. Also we now have `mocha_test` examples in the repo with no need for a custom rule.

**Pull request closed without merging**
