### PR TITLE
test: add grpc package to test its postinstall in CI

### PR DESCRIPTION
**Pull request by gregmagolan**
Testing to see if I can reproduce an error observed elsewhere:

```
error /builds/wemaintain/backend/node_modules/grpc: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --library=static_library
Arguments: 
Directory: /builds/wemaintain/backend/node_modules/grpc
Output:
internal/modules/cjs/loader.js:638
    throw err;
    ^
Error: Cannot find module '../'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/builds/wemaintain/backend/node_modules/grpc/node_modules/.bin/node-pre-gyp:15:20)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
)
```

### CODE REVIEW

**Comment by gregmagolan** [comment]
Yup. That was easy to reproduce.

**Comment by gregmagolan** [comment]
/cc @alexeagle 

I've dealt with a similar issue before but I can't recall what the underlying problem is.

I can't reproduce this locally on OSX even tho it fails on macos on buildkite:

```
ERROR: An error occurred during the fetch of repository 'npm':
--
  | yarn_install failed: yarn install v1.19.1
  | [1/4] Resolving packages...
  | [2/4] Fetching packages...
  | info @bazel/bazel-linux_x64@2.0.0: The platform "darwin" is incompatible with this module.
  | info "@bazel/bazel-linux_x64@2.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
  | info @bazel/bazel-win32_x64@2.0.0: The platform "darwin" is incompatible with this module.
  | info "@bazel/bazel-win32_x64@2.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
  | info @bazel/buildifier-linux_x64@0.26.0: The platform "darwin" is incompatible with this module.
  | info "@bazel/buildifier-linux_x64@0.26.0" is an optional dependency and failed compatibility check. Excluding it from installation.
  | info @bazel/buildifier-win32_x64@0.26.0: The platform "darwin" is incompatible with this module.
  | info "@bazel/buildifier-win32_x64@0.26.0" is an optional dependency and failed compatibility check. Excluding it from installation.
  | info @bazel/buildozer-linux_x64@0.29.0: The platform "darwin" is incompatible with this module.
  | info "@bazel/buildozer-linux_x64@0.29.0" is an optional dependency and failed compatibility check. Excluding it from installation.
  | info @bazel/buildozer-win32_x64@0.29.0: The platform "darwin" is incompatible with this module.
  | info "@bazel/buildozer-win32_x64@0.29.0" is an optional dependency and failed compatibility check. Excluding it from installation.
  | [3/4] Linking dependencies...
  | [4/4] Building fresh packages...
  | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
  | (warning " > tsickle@0.33.1" has incorrect peer dependency "typescript@3.1.3".
  | error /Users/buildkite/builds/bk-imacpro-19/bazel/rules-nodejs-nodejs/node_modules/grpc: Command failed.
  | Exit code: 1
  | Command: node-pre-gyp install --fallback-to-build --library=static_library
  | Arguments:
  | Directory: /Users/buildkite/builds/bk-imacpro-19/bazel/rules-nodejs-nodejs/node_modules/grpc
  | Output:
  | internal/modules/cjs/loader.js:797
  | throw err;
  | ^
  |  
  | Error: Cannot find module '../'
  | Require stack:
  | - /Users/buildkite/builds/bk-imacpro-19/bazel/rules-nodejs-nodejs/node_modules/grpc/node_modules/.bin/node-pre-gyp
  | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
  | at Function.Module._load (internal/modules/cjs/loader.js:687:27)
  | at Module.require (internal/modules/cjs/loader.js:849:19)
  | at require (internal/modules/cjs/helpers.js:74:18)
  | at Object.<anonymous> (/Users/buildkite/builds/bk-imacpro-19/bazel/rules-nodejs-nodejs/node_modules/grpc/node_modules/.bin/node-pre-gyp:15:20)
  | at Module._compile (internal/modules/cjs/loader.js:956:30)
  | at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
  | at Module.load (internal/modules/cjs/loader.js:812:32)
  | at Function.Module._load (internal/modules/cjs/loader.js:724:14)
  | at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  | code: 'MODULE_NOT_FOUND',
  | requireStack: [
  | '/Users/buildkite/builds/bk-imacpro-19/bazel/rules-nodejs-nodejs/node_modules/grpc/node_modules/.bin/node-pre-gyp'
  | ]
  | }
  | )
  | ERROR: no such package '@npm//': yarn_install failed: yarn install v1.19.1
```

Tristan from WeMaintain can't reproduce it locally on Linux or even locally in a docker image.

It's a mystery.

**Comment by Toxicable** [comment]
if it's macos only then might it be the same one we see here https://github.com/bazelbuild/rules_nodejs/issues/1527 ?

**Comment by gregmagolan** [comment]
Happens on linux as well both in CircleCI and buildkite envs. Somehow we've only observed it on CI on both linux and osx.

**Comment by alexeagle** [comment]
I assume you tried launching the docker container that CI uses and run through the build there? And SSH to the CI machine to see the state it's in after setup steps?

**Comment by gregmagolan** [comment]
Tristan tried that with the failing docker container locally and couldn't reproduce. My next steps are trying the CircleCI container & then SSH-ing into Circle and debugging there.

**Pull request closed without merging**
