### PR TITLE
fix(jasmine): fix runner when using Jasmine 4

### PR DESCRIPTION
**Pull request by jstuder-gh**
The onComplete method was removed in version 4.0. Changed to use the
results returned from execute to determine exit code.

Also changed spec retrieval in the sharding scenarios as the prior way
using instanceof no longer works as before.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ X] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #3289

## Does this PR introduce a breaking change?

- [ ] Yes
- [ X] No

### CODE REVIEW

**Comment by jstuder-gh** [comment]
I had not encountered https://github.com/bazelbuild/rules_nodejs/pull/3283 before modifying locally and submitting this PR. The other submission has cleaner code for handling the results of the `execute` function and looks preferable in that regard.

This modification, in addition, changes some code used to determine node type in `getAllSpecs`, as the prior way using `instanceof` no longer works in Jasmine 4.

Between the two branches, you should have what you need for both Jasmine 3 and 4 to work with `jasmine_node_test`.

**Comment by jstuder-gh** [comment]
Signed CLA after submitting branch

**Comment by jstuder-gh** [comment]
Closing in favor of https://github.com/bazelbuild/rules_nodejs/pull/3283

**Comment by alexeagle** [comment]
thanks @jstuder-gh sorry you ended up with duplicate work!

**Comment by jstuder-gh** [comment]
No problem. My fault for not paying closer attention :)

**Pull request closed without merging**
