### PR TITLE
chore(examples): add example for ng packagr

### PR DESCRIPTION
**Pull request by lukasholzer**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

This example should demonstrate the usage of packaging an angular
library with the `ng_package` rule from [@angular/bazel](https://angular.io/guide/bazel) in combination with the `ts_library` rule in combination with the angular plugin.

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by alan-agius4** [comment]
@alexeagle, I got the same impression. 

I'd definitely recommend using `load("@npm//ng-packagr:index.bzl", "ng_packagr")` unless you really need more fine grain library builds.

**Comment by lukasholzer** [comment]
@alan-agius4 I did The steps suggested by the Bazel Angular Docs https://angular.github.io/bazel-builds/src/ng_package/ng_package.html#ng_package

So I've used the installed `@angular/bazel` package where the rule `load("@npm_angular_bazel//:index.bzl", "ng_package")` is coming from.

**Comment by alexeagle** [comment]
I think the Angular team is deprecating the `@angular/bazel` package (it was in Labs) so we'd rather not show users how to make new dependencies on it. The `ng_package` rule is likely to be removed from the public API. Instead we want everyone to use the supported mechanism which is the ng-packagr library.

**Comment by alexeagle** [comment]
It looks like we have an ng-packagr example already here
https://github.com/bazelbuild/rules_nodejs/blob/master/examples/angular_bazel_architect/angular.json#L139
so I think this can be closed?

**Comment by lukasholzer** [comment]
@alexeagle It is an example with the architect – I think there should be an example without using the architect as the architect only allows incremental rebuilds per library and not as granular as it should be with bazel. 

I'm not sure if the packagr is needed for the angular package format or if the same can be achieved with rollup? But I think there should be an example of creating an Angular publishable library (Angular Package Format) with the benefits of incremental builds.

**Comment by alan-agius4** [comment]
@jbedard, was also looking to do something similar.

**Comment by alan-agius4** [comment]
> @alexeagle It is an example with the architect – I think there should be an example without using the architect as the architect only allows incremental rebuilds per library and not as granular as it should be with bazel.

This is that same for this PR, there is no different in using my-packagr directly via using the architect-cli.

**Comment by jbedard** [comment]
This seems to be `@angular/bazel`, not `ng-packagr`...?

**Comment by alan-agius4** [comment]
Ohh, the title of this PR always confuses me 😓

**Comment by jbedard** [comment]
> Ohh, the title of this PR always confuses me 😓

I agree :P

**Comment by alexeagle** [comment]
updated the title to explain - the issue is when we drop `@angular/bazel` you lose the `ng_package` rule and it would be nice to have a replacement

**Comment by jbedard** [comment]
I was trying `ng-packagr` but as a plain npm package it gets invoked quite differently then `ng_package`. I got `ng_package` working (thanks @gregmagolan !) by doing: https://github.com/angular/angular/pull/37727#issuecomment-656878664

**Comment by alexeagle** [comment]
Yeah given time constraints I think you should stick with @angular/bazel for now.
Other angular ecosystem projects like components and ngrx use it so there's no risk it disappears.

**Comment by alan-agius4** [comment]
@alexeagle, actually it seems that NGRX are moving away from Bazel in favor of NX with ng-packagr.

**Pull request closed without merging**
