### PR TITLE
Linux ppc64le support

### PR DESCRIPTION
**Pull request by npanpaliya**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
This PR will make rules_nodejs compatible to work on linux ppc64le systems.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]
Awesome, thank you!

**Comment by npanpaliya** [comment]
@alexeagle - Thank you for the review and your approval on this PR. Can it be merged now?

**Comment by alexeagle** [comment]
shoot I just caused another merge conflict on it from another bot commit to this file

**Comment by alexeagle** [comment]
oh you added a merge commit rather than rebasing your changes. That results in a non-linear history where things like bisecting are hard.  I'll fix it...

**Comment by alexeagle** [comment]
I am failing to clean up the git history after a few attempts. Could you rebase this with no merge commits please? Otherwise I can manually make the same edits but it won't use your authorship.

**Comment by alexeagle** [comment]
okay I think I wrangled it now ...

**Review by alexeagle — APPROVED** [review]

**Comment by npanpaliya** [comment]
Ohh, I'm sorry for using git merge instead of git rebase. And thank you for cleaning up my branch code and merging this PR.

**Pull request merged**
