### PR TITLE
chore: update NodeJS to LTS 12.13.0 and yarn to 1.19.1 version

### PR DESCRIPTION
**Pull request by siberex**
## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe:

Node version bump to current LTS.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

Builds not compatible with Node 12 could fail.

Builds relying on native dependencies in case if binaries for NODE_MODULE_VERSION=72 are not yet published for such dependency, will definitely fail (`bcrypt`, etc.).

Solution for such builds is quite straightforward though: use specific Node version in `node_repositories` definition in `WORKSPACE` file:

```
node_repositories(
    node_version = "10.16.0",
)
```

### CODE REVIEW

**Comment by siberex** [comment]
Looks like that one could be solved by upgrading dependencies for `packages/labs/src/protobufjs`: jsdoc peer dependency `requizzle` is failing due to this: https://github.com/hegemonic/requizzle/issues/6

**Comment by alexeagle** [comment]
FYI I mirrored the four new files to the bazel-mirror URL

**Comment by alexeagle** [comment]
Failure is 
```

Error: Command failed: npm --silent install chalk@^2.4.1 uglify-js@^3.3.25
--
  | at checkExecSyncError (child_process.js:621:11)
  | at Object.execSync (child_process.js:657:15)
  | at modInstall (/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/execroot/build_bazel_rules_nodejs/_tmp/a9ddbc4a3bd0efb73f565c7ee0d23be5/_bazel_buildkite-agent/e3ca3e1b861f802860d296ca8cbb6b5b/sandbox/linux-sandbox/148/execroot/examples_protocol_buffers/bazel-out/host/bin/external/npm_bazel_labs/protobufjs/pbjs.sh.runfiles/build_bazel_rules_typescript_protobufs_compiletime_deps/node_modules/protobufjs/cli/util.js:129:19)


```

looks like the action wants to write to the node_modules which is probably a read-only filesystem. Do you know what we need to install to prevent protobufjs doing this?

**Comment by siberex** [comment]
Issue is that `protobuf.js` is trying to npm install stuff programmatically:
https://github.com/protobufjs/protobuf.js/blob/69623a91c1e4a99d5210b5295a9e5b39d9517554/cli/util.js#L129

I don't know how to deal with it yet

**Pull request merged**
