### PR TITLE
Now places data relative to package.json

### PR DESCRIPTION
**Pull request by jroylance**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently, Bazel will place data dependencies relative to the project root. 

Issue Number: N/A

## What is the new behavior?

After this change, Bazel will place data dependencies relative to project.json

## Does this PR introduce a breaking change?

- [X] Yes
- [ ] No

Ensure that all data is referred to relative to package.json, rather than the project root. 

## Other information

### CODE REVIEW

**Comment by JaredNeil** [comment]
@alexeagle, This is a fix for the problem with postinstall scripts I mentioned to you at ng-conf. @jroylance is an intern on our team for the summer.

Previously the `npm_install` and `yarn_install` would break the relative paths between `package.json` and any `data` files if the `package.json` was not at the root of the workspace. This change maintains the relative paths no matter where the `package.json` is.

Unfortunately this probably does count as a breaking change.
One new limitation that this introduces is that all `data` to a `npm_install` must be in or below the package that `package.json` is in, but I think that fits more closely with the intent of a `package.json` since reaching out of the package to find or run files seems very fragile.

**Comment by alexeagle** [comment]
Thanks, this makes sense to me. Could you fix the two broken circleci failures?

Note that we'll soon land #704 which will mostly obviate the need for this - we'll expect that most users don't pass `data[]` to `yarn_install`/`npm_install` since the install will run in the project directory.

**Comment by alexeagle** [comment]
@jroylance now that `data` is unneeded, do you still plan to work on this?

**Comment by JaredNeil** [comment]
No, I don't think it's worth doing any more if installation is actually happening in the source tree. I'm fine with just closing the PR.

**Pull request closed without merging**
