### PR TITLE
chore: switch buildifier lint to blocklist

### PR DESCRIPTION
**Pull request by alexeagle**
tidy up a couple of warnings at the same time.
This lets us burn them down by removing exclusions.

### CODE REVIEW

**Review by mattem — APPROVED** [review]

**Comment by alexeagle** [comment]
@googlebot I fixed it.

**Comment by alexeagle** [comment]
@googlebot I fixed it.

**Comment by alexeagle** [comment]
@googlebot I fixed it.

**Comment by alexeagle** [comment]
Hmm we signed the corporate SLA a couple days ago, what else does @googlebot want from me? :(
Maybe I have to wait longer for a googler to process the cla

**Comment by alexeagle** [comment]
thanks for replying @googlebot you are my friend for sure. How's the datacenter these days?

**Comment by alexeagle** [comment]
@googlebot I fixed it.

**Comment by alexeagle** [comment]
@googlebot I consent.

**Pull request merged**
