### PR TITLE
fix ts_proto_library handling of external proto_library

### LINKED ISSUE #1946: ts_proto_library: Cannot depend on external proto_library
# 🐞 bug report

### Affected Rule

ts_proto_library (grpc version in the labs project)

### Is this a regression?

No. I don't think this feature was ever supported.

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

This works:
```shell
git clone https://github.com/gonzojive/ts_proto_help.git
cd original_example
bazel test //...
```

This folder is the same but has a dependency on "google/type/latlng.proto":

```shell
git clone https://github.com/gonzojive/ts_proto_help.git
cd updated_example
bazel build //:car_proto
# INFO: Build completed successfully, 1 total action
bazel test //...
# fails with below error
```

## 🔥 Exception or Error

```
$ bazel test //...
INFO: Build option --define has changed, discarding analysis cache.
INFO: Analyzed 24 targets (0 packages loaded, 10430 targets configured).
INFO: Found 19 targets and 5 test targets...
ERROR: /home/red/git/demos/ts_proto_help/updated_example/BUILD.bazel:86:1: Bundling JavaScript bundle.js [rollup] failed (Exit 1) rollup.sh failed: error executing command bazel-out/host/bin/external/npm/rollup/bin/rollup.sh bazel-out/k8-fastbuild/bin/app.mjs --output.file bazel-out/k8-fastbuild/bin/bundle.js --format iife --config ... (remaining 6 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox

bazel-out/k8-fastbuild/bin/app.mjs → bazel-out/k8-fastbuild/bin/bundle.js...
[!] Error: Could not resolve './google/type/latlng_pb' from node_modules/updated_example_ws/car_pb.mjs
Error: Could not resolve './google/type/latlng_pb' from node_modules/updated_example_ws/car_pb.mjs
    at error (/home/red/.cache/bazel/_bazel_red/ec4cc2e04810cf9c9e7fbb006efc9622/sandbox/linux-sandbox/525/execroot/updated_example_ws/node_modules/rollup/dist/rollup.js:9419:30)
    at ModuleLoader.handleMissingImports (/home/red/.cache/bazel/_bazel_red/ec4cc2e04810cf9c9e7fbb006efc9622/sandbox/linux-sandbox/525/execroot/updated_example_ws/node_modules/rollup/dist/rollup.js:16467:17)
    at ModuleLoader.<anonymous> (/home/red/.cache/bazel/_bazel_red/ec4cc2e04810cf9c9e7fbb006efc9622/sandbox/linux-sandbox/525/execroot/updated_example_ws/node_modules/rollup/dist/rollup.js:16518:26)
    at Generator.next (<anonymous>)
    at fulfilled (/home/red/.cache/bazel/_bazel_red/ec4cc2e04810cf9c9e7fbb006efc9622/sandbox/linux-sandbox/525/execroot/updated_example_ws/node_modules/rollup/dist/rollup.js:40:28)

INFO: Elapsed time: 1.995s, Critical Path: 1.30s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
//:dummy_test                                                   (cached) PASSED in 0.1s
//:devserver_test_chromium-local                                      NO STATUS
//:prodserver_test_chromium-local                                     NO STATUS
//:test_chromium-local                                                NO STATUS
//:test_firefox-local                                                 NO STATUS

Executed 0 out of 5 tests: 1 test passes and 4 were skipped.
FAILED: Build did NOT complete successfully
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
   Ubuntu 18.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 3.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:32:27 2020 (1587551547)
Build timestamp: 1587551547
Build timestamp as int: 1587551547
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "84abf7ac4234a70924628baa9a73a5a5cbad944c4358cf9abdb4aab29c9a5b77",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/1.7.0/rules_nodejs-1.7.0.tar.gz"],
)
  </code>
</pre>

**Anything else relevant?**

https://github.com/gonzojive/ts_proto_help has an altered version of ts_proto_library that I'm using to fix issues from the labs version. You can toggle it on and off in the BUILD.bazel file:

```skylark
load("@npm_bazel_labs//:index.bzl", "ts_proto_library")
#load("@updated_example_ws//updated_rules:ts_proto_library_fix.bzl", "ts_proto_library")
```

One issue with the current ts_proto_library is that `_build_protoc_command` uses `ctx.var["BINDIR"]` as the output directory passed to protoc. This is not correct for external repositories, which will typically output to `bazel-bin/external/<repo name>/<path to input proto?>{_pb.js,...}`. This results in the wrong input and output path being passed into the `change_import_style` binary.

`change_import_style` also has a bug in that it tolerates nonexistent input files. This is not appropriate for the non-gRPC `_pb.js` file that is generated for each input proto, which should always be created by protoc afaict. I think this bug is responsible for confusing behavior in other open issues where generated proto libraries contain no exports.

Two further stumbling blocks that make it unclear how to fix:

1. I'm not quite sure how one is supposed to import ts_library rules declared in non-npm external repositories.  This isn't documented in the [ts_library docs](https://bazelbuild.github.io/rules_nodejs/TypeScript.html). The docs say that imports to ts_libraries defined in the workspace can be done by prefixing the name of the workspace.

2. How should one import an external proto in a `.ts` file if there is no `ts_proto_library` for that proto?

### PR DESCRIPTION
**Pull request by tsawada**
Currently, ts_proto_library generates meaningless .js files for external proto_library.
This commit fix that by
* change_import_style.js to distinguish input/output path so that it works even when they are different.
    * for internal proto_library, these paths are the same, but they are different for external ones, which change_import_style.js couldn't handle nicely.
* ts_proto_library_aspect to pass the correct .js path in between protoc and change_import_style

Closes #1946

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
ts_proto_library generates meaningless (semantically empty) `.js` and `.mjs` files for `proto_library` defined in external workspaces.
For `.mjs`, the content is always `const exportVariable = {}`

Issue Number: #1946, also #1820

## What is the new behavior?
proto_library correctly generates non-empty `.js` files for external proto_library.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

I'm not sure if we are supposed to generate `.js` files under `bazel-out/*/bin/external/_external_ws_name_/`, because other `protoc`-generated js code refer them via singly-rooted `importpath` under `bazel-out/*/bin/`.
For example, when we `import "google/protobuf/timestamp.proto";` within .proto files, that becomes `require("google/protobuf/timestamp_pb")` in the protoc generated code (assuming it's not WELL_KNOWN), not `require("external/com_google_protobuf/timestamp_pb")`.
I workaround this by telling bundlers where each file actually is, which isn't very clean.

### CODE REVIEW

**Comment by tsawada** [comment]
I appreciate any feedback on this PR.

I am not sure why Windows build fails. The error message look unrelated to what I changed. Any hints?
https://buildkite.com/bazel/rules-nodejs-nodejs/builds/9500#9a136599-2186-4961-ad9d-7c84b114740c/714-734

Thanks!

**Comment by tsawada** [comment]
@alexeagle @mrmeku would you take a look? Thanks in advance!

**Comment by mrmeku** [comment]
Sorry I missed this! I'll take a look today

**Review by mrmeku — APPROVED** [review]

**Comment by tsawada** [comment]
@mrmeku Thanks for taking a look! Is there anything I can do to get this merged? Should I rebase? I'm concerned if the Windows test breakage is blocking the merge.

**Comment by mattem** [comment]
@tsawada Are you able to rebase this? Thanks!

**Comment by tsawada** [comment]
@mattem Thanks. Rebased and force-pushed.

**Comment by alexeagle** [comment]
Thanks!!

**Comment by alexeagle** [comment]
Hi @tsawada sad news - our next release is in progress on the 4.x branch, and this PR doesn't merge over there. It's due to https://github.com/bazelbuild/rules_nodejs/commit/5f26d0ff0a5a9e5fd548e82bba60e110d02579ca#diff-aebefa9d3e75a151707845c1453e5b65c7f56b39614e683c7267d29205602bbe which totally deletes `change_import_style.js`

That commit is released in 4.0.0-beta.1 - could you check if the original problem you found here is also reproducible in that release? If so we'll need to port your fix to the 4.x branch manually.

Thanks!

**Comment by tsawada** [comment]
@alexeagle I'll try `4.0.0-rc.0` but it'll take a while. do you have any timeline for the 4.0.0 release?

**Comment by alexeagle** [comment]
hey @tsawada just checking in here again, we're on 4.2.0 now so there's been a while with releases not including your fix. When you have a minute could you check if your original problem is still reproduceable?

**Comment by aaahrens** [comment]
This is a really biting issue <.< would hope to see it merged  in.

**Pull request merged**
