### PR TITLE
fix(exmaples/nestjs): add module_name field in ts_library

### PR DESCRIPTION
**Pull request by lovepocky**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by alexeagle** [comment]
Please fill in the PR template. I don't understand the motivation for this change. Is there a bug with the current code?

**Comment by lovepocky** [comment]
current behavior (will run into node shell): 
```
$ bazel run src:server                  
INFO: Invocation ID: 708e62e1-1b6b-49c4-9409-194a31ed547c
INFO: Analyzed target //src:server (154 packages loaded, 7336 targets configured).
INFO: Found 1 target...
Target //src:server up-to-date:
  dist/bin/src/server.sh
  dist/bin/src/server_loader.js
  dist/bin/src/server_require_patch.js
INFO: Elapsed time: 3.455s, Critical Path: 0.17s
INFO: 7 processes: 1 remote cache hit, 6 internal.
INFO: Build completed successfully, 7 total actions
INFO: Build completed successfully, 7 total actions
Welcome to Node.js v12.13.0.
Type ".help" for more information.
> 
```

after fix:
```
$ bazel run src:server                                                                                                                                                                                             
INFO: Invocation ID: d5620fe9-a50b-4776-b5c7-86a5e5bdc2a6                                                                                                                                                          
INFO: Analyzed target //src:server (1 packages loaded, 5 targets configured).                            
INFO: Found 1 target...                                                                                                                                                                                            
Target //src:server up-to-date:                                                                          
  dist/bin/src/server.sh                                                                                                                                                                                           
  dist/bin/src/server_loader.js                                                                                                                                                                                    
  dist/bin/src/server_require_patch.js                                                                                                                                                                             
INFO: Elapsed time: 0.642s, Critical Path: 0.06s                                                         
INFO: 7 processes: 1 remote cache hit, 6 internal.                                                                                                                                                                 
INFO: Build completed successfully, 7 total actions                                                      
INFO: Build completed successfully, 7 total actions                                                      
[Nest] 1808303   - 10/27/2020, 8:06 AM   Worker 1808310 is online.                                       
[Nest] 1808303   - 10/27/2020, 8:06 AM   Worker 1808311 is online. +1ms                                  
[Nest] 1808303   - 10/27/2020, 8:06 AM   Worker 1808313 is online. +0ms                                  
[Nest] 1808303   - 10/27/2020, 8:06 AM   Worker 1808318 is online. +0ms                                                                                                                                            
[Nest] 1808303   - 10/27/2020, 8:06 AM   Worker 1808325 is online. +1ms                                                                                                                                            
[Nest] 1808303   - 10/27/2020, 8:06 AM   Worker 1808331 is online. +0ms                                  
[Nest] 1808303   - 10/27/2020, 8:06 AM   Worker 1808343 is online. +1ms                           
[Nest] 1808303   - 10/27/2020, 8:06 AM   Worker 1808352 is online. +0ms                                                                                                                                            
[Nest] 1808303   - 10/27/2020, 8:06 AM   Worker 1808359 is online. +21ms                                 
[Nest] 1808303   - 10/27/2020, 8:06 AM   Worker 1808367 is online. +3ms                                                                                                                                            
[Nest] 1808303   - 10/27/2020, 8:06 AM   Worker 1808369 is online. +3ms                                                                                                                                            
[Nest] 1808303   - 10/27/2020, 8:06 AM   Worker 1808371 is online. +32ms                                                                                                                                           
[Nest] 1808313   - 10/27/2020, 8:06 AM   [NestFactory] Starting Nest application...        

...
```

**Comment by lovepocky** [comment]
@googlebot I signed it!

**Review by alexeagle — APPROVED** [review]

**Comment by alexeagle** [comment]
thanks!

**Pull request merged**
