### PR TITLE
Cleanups for compatibility with future Bazel releases

### LINKED ISSUE #431: Fix Bazel incompatible changes
I'd like to be able to build rules_nodejs with `--all_incompatible_changes`:
  `cd rules_nodejs && bazel build //... --all_incompatible_changes`

It may not be possible to fix every issue now due to transitive dependencies, but we should try to fix the issues from this repository.

### PR DESCRIPTION
**Pull request by laurentlb**
- No implicit flattening of depsets
- Separate tools from inputs in an action
- Update some dependencies

Fixes #431

### CODE REVIEW

**Comment by laurentlb** [comment]
This now works:
`bazel test //... --all_incompatible_changes --incompatible_no_transitive_loads=false --incompatible_no_support_tools_in_action_inputs=false `

`--incompatible_no_transitive_loads=false` is needed because of the Go dependency
`--incompatible_no_support_tools_in_action_inputs=false` is needed because of a bzl file shipped with Bazel

**Comment by laurentlb** [comment]
ping?

**Comment by laurentlb** [comment]
With my latest commits, it's all fixed!

Tested:
`bazel0.20 test //... --all_incompatible_changes`

**Comment by mgechev** [comment]
LGTM, I'll let @alexeagle and @gregmagolan give the final approval because they have more context.

**Comment by laurentlb** [comment]
Thanks!
Yes, we're looking at enabling this on the CI for all rules.

**Comment by laurentlb** [comment]
please merge (I don't have write access)

**Pull request merged**
