### PR TITLE
Correct node and npm paths on Windows

### PR DESCRIPTION
**Pull request by davschne**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: [3399](https://github.com/bazelbuild/rules_nodejs/issues/3399)

## What is the new behavior?

Uses the correct paths to the `node` and `npm` executables on Windows

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Change authored by [flemminglundahl](https://github.com/flemminglundahl)

### CODE REVIEW

**Comment by davschne** [comment]
@mattem, @gregmagolan, @alexeagle, I'm trying to figure out why the Windows NodeJS packages being used in BuildKite CI have the executable as `bin/node.cmd` rather than `node.exe`. Every Windows Node package I've seen has `node.exe` in the root directory and no `bin/node.cmd` at all. Can you shed some light on this? Where do you get your Node packages?

**Comment by alexeagle** [comment]
We generate the node.cmd as a wrapper around node.exe somewhere. Does that help?

**Comment by alexeagle** [comment]
The Buildkite instance is run by the bazel team (using https://github.com/bazelbuild/continuous-integration )
so the config is https://github.com/bazelbuild/rules_nodejs/blob/stable/.bazelci/presubmit.yml

The `SCRIPT_DIR` and `PATH` variables in node.cmd are load-bearing, because otherwise subprocesses will run the node binary they find on the machine instead of the bazel-managed one
https://github.com/bazelbuild/rules_nodejs/blob/stable/nodejs/repositories.bzl#L246-L249
so I don't think it's as simple as ditching that wrapper and running node.exe directly instead.

There's probably some way to keep that four-line wrapper, but still call the node.exe that's vendored into the repo...

**Comment by davschne** [comment]
Cool, thanks for pointing me to the CI config, @alexeagle, and for providing clarity regarding the wrapper. I'll look into the problem further and see if I can find a solution that makes the wrapper work for vendored Node.

**Comment by davschne** [comment]
@alexeagle, it looks like the `node` and `npm` wrappers get created in the repository rule `node_repositories`. At present, it looks like `node_repositories` isn't designed to be used when using local vendored Node. I'm thinking the most straightforward solution is to always use `node_repositories` (or `yarn_repositories`), even for local vendored Node, if we want to ensure the wrappers get created. I'll look into what modifications to these repository rules would be required, but I did want to check with you to see what you think about this approach.

While investigating, I also noticed that `examples/vendored_node_and_yarn` fails to build for me on Windows. It gives essentially the same error message as documented in #3399. Seems that it would be good to have a test for this in CI.

**Comment by alexeagle** [comment]
Yup I think that solution can work. At some point we got too overwhelmed and dropped that windows CI coverage. Maybe even due to the same bug... sorry about that

**Comment by davschne** [comment]
I'm working on a revision in which `node_repositories` can take a new attribute, `node_label`, which references the Node executable in each platform-specific vendored Node repository. That way the wrapper script can delegate to the correct executable after setting up the `PATH` variable. It could be used like this:

```starlark
node_repositories(
    node_label = {
        "linux_amd64": "@vendored_node_linux_amd64//:bin/node",
        "darwin_amd64": "@vendored_node_darwin_amd64//:bin/node",
        "windows_amd64": "@vendored_node_windows_amd64//:node.exe",
    },
)
```

`node_repositories` would find the `npm-cli.js` and `npx-cli.js` scripts in the vendored repos relative to the executable referenced by the label, since Node packages use a predictable layout.

@alexeagle, any thoughts on this interface?

**Pull request closed without merging**
