### PR TITLE
[wip] Fix RUNFILES resolution for nested tools

### PR DESCRIPTION
**Pull request by samschlegel**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
  - I can add a test case for the failing behavior if that's desired 
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #1910 

To clarify the cause of the issue, when a `node_binary` (X), is invoked from another tool (Y) the current RUNFILES resolution prefers X's runfiles directory when it should choose Y's. This is normally fine if X's runfiles directory doesn't exists, such as when it hasn't been built yet, but it breaks when it does. Y's runfiles directory should always be a superset of X's runfiles directory, so there's no reason to choose X's over Y's.

## What is the new behavior?

This PR switches to using the default `RUNFILES_DIR`, which will prefer the correct directory.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

There were comments that `${PWD}/${RUNFILES_DIR}` is not always correct. I'm not sure what cases this is referring to, as that should always be correct. The only thing I can think of is that it's possible that X's runfiles are not contained in Y's runfiles, but that's an issue with the rule implementation of Y, not with RUNFILES_DIR.

### CODE REVIEW

**Comment by samschlegel** [comment]
Ah right, `readlink -f` doesn't work on Mac, and Windows doesn't have the DIR. 😢 Will try and just fix the existing lookup instead.

**Comment by samschlegel** [comment]
Added a failing test. The test succeeds in a clean env, but fails after building `//internal/node/test:nested_tool`. Not sure how to encode this in a Bazel test itself so will probably have to add some kind of ordering in another way.

Won't have time to tackle this the rest of the week but at least there's a fairly minimal repro 😄

**Comment by alexeagle** [comment]
Ooh I was wondering if you were going to adopt Rome over there :)
Thanks for the repro, that's a good start. We might be able to test that ordering in a bazel-in-bazel test, each of our examples/e2e directories has one of those.
Not sure when we'll have time to dig in, but I'd like to do some bugfix sprint after 2.0 final

**Comment by samschlegel** [comment]
> Ooh I was wondering if you were going to adopt Rome over there :)

Heh, probably at some point. I'm not super familiar with our front-end side of things. I mostly just want to use tools like `cdk8s` to build manifests for use with `rules_k8s` to replace Jsonnet 😅 

> Thanks for the repro, that's a good start. We might be able to test that ordering in a bazel-in-bazel test, each of our examples/e2e directories has one of those.
> Not sure when we'll have time to dig in, but I'd like to do some bugfix sprint after 2.0 final

🙏

**Pull request closed without merging**
