### PR TITLE
build: update to bazel 0.27.0rc5

### PR DESCRIPTION
**Pull request by gregmagolan**
Testing against Bazel 0.27.0rc5 as I saw an unexpected error locally:

```
Building package typescript //:npm_package
checking deps: jasmine
all deps built
+ bazel build --workspace_status_command=../../scripts/current_version.sh //:npm_package
Starting local Bazel server and connecting to it...
DEBUG: Rule 'build_bazel_rules_typescript' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1559861420 -0700"
DEBUG: Call stack for the definition of repository 'build_bazel_rules_typescript' which is a git_repository (rule definition at /private/var/tmp/_bazel_greg/b90b17756fe48c3e5b8d42d3ed61ee61/external/bazel_tools/tools/build_defs/repo/git.bzl:252:18):
 - /Users/greg/google/gregmagolan/rules_nodejs/packages/typescript/WORKSPACE:44:1
INFO: SHA256 (https://github.com/manekinekko/rules_sass/archive/9862dfc96a4a1f66fe171ef5e043b29853e8445b.zip) = 6035f25dbcd1e5575a681f5d7b9d9821dde09fcf73ccea053d1bc1c9523b1a2a
DEBUG: Rule 'io_bazel_rules_sass' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "6035f25dbcd1e5575a681f5d7b9d9821dde09fcf73ccea053d1bc1c9523b1a2a"
DEBUG: Call stack for the definition of repository 'io_bazel_rules_sass' which is a http_archive (rule definition at /private/var/tmp/_bazel_greg/b90b17756fe48c3e5b8d42d3ed61ee61/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /private/var/tmp/_bazel_greg/b90b17756fe48c3e5b8d42d3ed61ee61/external/build_bazel_rules_nodejs/package.bzl:40:5
 - /Users/greg/google/gregmagolan/rules_nodejs/packages/typescript/WORKSPACE:31:1
ERROR: /Users/greg/google/gregmagolan/rules_nodejs/packages/typescript/BUILD.bazel:71:20: **kwargs arguments are not allowed in BUILD files. Pass the arguments in explicitly.
ERROR: error loading package '': Package '' contains errors
INFO: Elapsed time: 17.784s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
```

### CODE REVIEW

**Comment by gregmagolan** [comment]
Does 0.27 get confused between
```
replacements = dict(
        COMMON_REPLACEMENTS,
        **{
            # This BEGIN-DEV fencing is required as files pulled in from
            # @build_bazel_rules_typescript//:npm_bazel_typescript_package
            # use this alternate fencing
            "(#|\/\/)\\s+BEGIN-DEV-ONLY[\\w\W]+?(#|\/\/)\\s+END-DEV-ONLY": "",
            # Do a simple replacement needed to make the local development differ
            # from how our release is used.
            "//devserver:devserver_bin": "//devserver",
            # This file gets vendored into our repo
            "@build_bazel_rules_typescript//internal:common": "//internal:common",
        }
    ),
```
and `**kwargs`?
Error seen locally is `ERROR: /Users/greg/google/gregmagolan/rules_nodejs/packages/typescript/BUILD.bazel:71:20: **kwargs arguments are not allowed in BUILD files. Pass the arguments in explicitly.`

**Comment by gregmagolan** [comment]
In CI seeing this:
```
Bazel version:
bazel: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by bazel)
Exited with code 1
```
so looks like we'll need to update to a newer dockerized linux

**Comment by Toxicable** [comment]
Just tried 0.27.0rc5 on our repo and saw this one
```
Traceback (most recent call last):
        File "/home/f.wiles/workspace/libs/forms/BUILD.bazel", line 13
                ng_module(name = 'forms')
        File "/home/f.wiles/.cache/bazel/_bazel_f.wiles/4e95cbad76bfb4ed000904165db39268/external/npm_angular_bazel/src/ng_module.bzl", line 602, in _ng_module_impl
                ts_providers_dict_to_struct(ng_module_impl(ctx, compile_ts))
        File "/home/f.wiles/.cache/bazel/_bazel_f.wiles/4e95cbad76bfb4ed000904165db39268/external/npm_angular_bazel/src/ng_module.bzl", line 602, in ts_providers_dict_to_struct
                ng_module_impl(ctx, compile_ts)
        File "/home/f.wiles/.cache/bazel/_bazel_f.wiles/4e95cbad76bfb4ed000904165db39268/external/npm_angular_bazel/src/ng_module.bzl", line 560, in ng_module_impl
                ts_compile_actions(ctx, is_library = True, deps = [d fo...))], <4 more arguments>)
        File "/home/f.wiles/.cache/bazel/_bazel_f.wiles/4e95cbad76bfb4ed000904165db39268/external/npm_bazel_typescript/internal/common/compilation.bzl", line 261, in ts_compile_actions
                outputs(ctx, ctx.label, srcs_files)
        File "/home/f.wiles/.cache/bazel/_bazel_f.wiles/4e95cbad76bfb4ed000904165db39268/external/npm_angular_bazel/src/ng_module.bzl", line 541, in outputs
                _expected_outs(ctx)
        File "/home/f.wiles/.cache/bazel/_bazel_f.wiles/4e95cbad76bfb4ed000904165db39268/external/npm_angular_bazel/src/ng_module.bzl", line 272, in _expected_outs
                ctx.new_file(ctx.genfiles_dir, (ctx.label.name ..."))
Use ctx.actions.declare_file instead of ctx.new_file. 
Use --incompatible_new_actions_api=false to temporarily disable this check.
```

**Comment by gregmagolan** [comment]
Thanks @Toxicable. Put up https://github.com/angular/angular/pull/31019 to fix that.

**Comment by gregmagolan** [comment]
Hmmmm. Now seeing

```
ERROR: /home/circleci/rules_nodejs/e2e/karma_typescript/BUILD.bazel:37:1: Compiling TypeScript (devmode) //:hello_world failed (Exit 1)
error TS2688: Cannot find type definition file for 'jasmine'.
error TS2688: Cannot find type definition file for 'long'.
error TS2688: Cannot find type definition file for 'node'.
```

on a number of e2e tests and one example. 🤔

**Comment by gregmagolan** [comment]
Replaced by https://github.com/bazelbuild/rules_nodejs/pull/864

**Pull request closed without merging**
