### PR TITLE
feat(karma): use Trusted Types policy when loading scripts for Karma

### PR DESCRIPTION
**Pull request by bjarkler**
When the Karma plugin is used in a testing environment that enforces
[Trusted Types](https://web.dev/trusted-types/), its loadFile functionality currently fails due to a
Trusted Types violation when assigning to script.textContent. This makes
it impossible to use the plugin with integration tests that ensure an
application is compatible with Trusted Types.

This is fixed by creating a Trusted Types policy specifically for the
Karma plugin, and use it to promote any loaded scripts to a TrustedScript
before assigning to script.textContent. This is done in a way that is
backwards compatible:
- The policy is `null` in browsers that don't yet support Trusted Types,
  in which case the original script string is used as before.
- When Trusted Types are supported in the browser but not enforced by
  the application, the browser treats the TrustedScript as if it were a
  string when it is assigned to script.textContent.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

This is part of an effort to bring Trusted Types support to Angular. In particular, this will unblock the use of Trusted Types in Angular's unit tests and integration tests.

Googler here, so CLA is not needed.

### CODE REVIEW

**Comment by alexeagle** [comment]
cool, can you fix the broken tests?
```
07 10 2020 16:10:17.235:INFO [Firefox 68.0.0 (Linux 0.0.0)]: Connected on socket kq0Un8jVgLE4z6wuAAAA with id 82691039
Firefox 68.0.0 (Linux 0.0.0) ERROR
  SyntaxError: missing catch or finally after try
  at /concatjs_bundle.js:10:4
```

**Review by alexeagle — APPROVED** [review]

**Comment by bjarkler** [comment]
> cool, can you fix the broken tests?

Sorry, my bad. Always test last minute changes! :)

Before merging, let me do one more run of the Angular test suite to make sure everything is working as expected.

**Comment by bjarkler** [comment]
Alright, did one more run and the change looks good from my end. Thanks for the quick review @alexeagle.

**Comment by bjarkler** [comment]
CC @engelsdamien @koto

**Comment by alexeagle** [comment]
Just pushed a commit to fix the broken angular integration test, could you rebase to validate this is green pls?

**Comment by bjarkler** [comment]
Rebased and it looks like it passes now. Thanks for fixing the integration test, @alexeagle.

**Pull request merged**
