### PR TITLE
Nextjs example

### PR DESCRIPTION
**Pull request by alexeagle**

### CODE REVIEW

**Comment by mrtnzlml** [comment]
Hi @alexeagle, just wanted to check-in. Did you have any luck with Bazel vs. Next.js? :) Would you happen to know how to overcome the issues blocking this PR?

**Comment by flolu** [comment]
Any updates on this? I think Next.js example would be highly valuable

**Comment by alexeagle** [comment]
So far it just hasn't been either funded by a company that needs it, or a fun hobby for someone in their spare time. Would love to work on this if some company needs it

**Comment by flolu** [comment]
Makes sense. What do you think is the estimated effort? (a couple days, weeks?)
We could add some funding, but our budget is small.

**Comment by alexeagle** [comment]
Hard to say, I don't think we even identified all the issues. Depends what other assumptions are broken by next tooling. ts_project took me about two weeks I think.

**Comment by flolu** [comment]
Btw the implementation with auto-generated `next` does work without `write_chdir_script` now.
But the [global styles issue](https://github.com/flolu/nextjs-bazel/issues/1) is still there. Other than that it works quite good, even with PWA support.

Do you think this is a bug in the `next` builder, or is there something "wrong" with Bazel?

**Pull request closed without merging**
