### PR TITLE
Fix incorrect link to managed dependencies

### PR DESCRIPTION
**Pull request by mangini**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
Link is invalid

Issue Number: N/A

## What is the new behavior?
Link is valid

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]
thanks!

**Comment by mattem** [comment]
Oh this went into master and not stable

**Comment by alexeagle** [comment]
That's strange how did it target master??

**Comment by mangini** [comment]
Not sure if the question if for me, but I will answer anyway. I searched for "workspace managed_directories" (or something similar) on Google, as I wanted to see some example usages of it, and I ended up in https://github.com/bazelbuild/rules_nodejs/blob/master/examples/angular/README.md (note the master branch). From there, I used Github inline editor, edited and sent the PR, which naturally targeted "master". Let me know if I need to do anything else or target a different branch, happy to cherry-pick if needed.

**Comment by alexeagle** [comment]
Interesting, seems like a GitHub bug. I've just deleted the `master` branch so now the pencil button workflow correctly targets the default branch (`stable`) so you could send the PR again?

**Comment by mangini** [comment]
Done, https://github.com/bazelbuild/rules_nodejs/pull/3075

**Pull request merged**
