### PR TITLE
Add an express example.

### PR DESCRIPTION
**Pull request by mattmoor**
This also adds a trivial non-http example (which I can delete if you prefer).

### CODE REVIEW

**Comment by alexeagle** [comment]
The contents look fine, but what's the objective? There is already an example of writing a program in js that links against a third-party library. If we add an express example, does that mean we ought to add an example for every third-party library? Or does this illustrate something the rollup example does not?

**Comment by mattmoor** [comment]
Writing web apps seems pretty core to Node.js.

If you don't think it's useful here, I'm happy to discard.  It'll probably end up being the basis for a `node_image` K8s "http" example / test [here](https://github.com/bazelbuild/rules_k8s/tree/master/examples/hellohttp).

... that is once I use it to figure out how to properly build `node_image` :)

**Comment by laat** [comment]
npm_install could be made more reproducible with a parameter specifying a `package-lock.json` file

**Comment by mattmoor** [comment]
@laat Sorry, I updated this branch without realizing we'd left this open.  See the discussion [here](https://github.com/bazelbuild/rules_nodejs/issues/63), but it is very much my intention that folks could (and probably would) use lock files with that rule.

**Pull request closed without merging**
