### PR TITLE
docs: add spica to adopter organization list

### PR DESCRIPTION
**Pull request by mattem**
cherry-pick of 16f0c0ef7a9ce3f2ff7c39d25f02f39fc7fd2338 that was merged to master

### CODE REVIEW

**Comment by thesayyn** [comment]
@googlebot I consent.

**Comment by thesayyn** [comment]
@mattem I guess it is good to go.

**Comment by mattem** [comment]
Yes, just need a approval from @alexeagle or another reviewer and I'll merge

**Review by alexeagle — APPROVED** [review]
🙏

**Pull request merged**
