### PR TITLE
fix(worker): check if the input digest present

### PR DESCRIPTION
**Pull request by thesayyn**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/bazelbuild/rules_nodejs/issues/2953

## What is the new behavior?

Check if the input digest is present.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by matthewjh** [comment]
Thanks @thesayyn

Just wondering, is there any test case that would have caught this, such as passing a directory src? If so, it could go in

//packages/typescript/test/ts_project/worker

**Comment by thesayyn** [comment]
I am still not sure about what was the root cause of this issue (cache-miss, directory, or something else). 

I might have to dig deeper to find the cause of this issue.

**Comment by thesayyn** [comment]
Could be: https://github.com/bazelbuild/bazel/blob/97643ad92d86179d21b2526e9f9804045d025f21/src/main/java/com/google/devtools/build/lib/actions/ActionCacheChecker.java#L714

**Review by alexeagle — APPROVED** [review]
We do need to merge this to fix the bug, but yes please keep digging to see where the missing test should go :)

**Pull request merged**
