### PR TITLE
docs: update rules_typescript e.g with a label a reader can copy paste

### PR DESCRIPTION
**Pull request by bweston92**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## Other information

I was trying `@build_bazel_rules_nodejs//packages/typescript:index.bzl` before seeing docs for other packages included with `rules_nodejs`, so this change might just save some time for a reader in the future.

### CODE REVIEW

**Comment by alexeagle** [comment]
Hmm, thanks for the PR - but there should be a spot in our docgen pipeline that does a replacement for all our internal labels to convert to user-facing labels. Looking to see what happened...

**Comment by bweston92** [comment]
Sweet, unable to help on that one. Hope it is easy enough :)

**Comment by alexeagle** [comment]
Well I'm happy to show where the code is if you're curious - in tools/stardoc/post-process-docs.js there's a regex which should get applied.

**Comment by bweston92** [comment]
@alexeagle thanks for the hint, submitted in #2760

**Comment by alexeagle** [comment]
yeah here's another spot, in the checked-in docs this is `@npm`
https://github.com/bazelbuild/rules_nodejs/blob/3.5.1/docs/Rollup.md#rollup_worker_bin
but on the new docsite it's `//packages` https://docs.aspect.dev/bazelbuild/rules_nodejs/3.5.1/packages/rollup/readme#rollup_bundle-rollup_worker_bin

it's because the new docsite isn't running this post-process-docs at all, it's wired into our Jekyll pipeline

**Pull request closed without merging**
