### PR TITLE
ci: teardown CircleCI configuration

### PR DESCRIPTION
**Pull request by thesayyn**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by alexeagle** [comment]
I turned off the "Active" bit on the circleci webhook

Screenshot from 2022-06-09 09-05-23

to allow this to go green and stop sending traffic to circleci which I think is the first step here.

Do we know what test coverage we've lost as a result?

**Comment by thesayyn** [comment]
> Do we know what test coverage we've lost as a result?

We've lost the coverage for web testing targets. for `chrome, firefox, and cypress` on ubuntu for `examples`, and only `firefox` on mac for `e2e`

**Comment by thesayyn** [comment]
Maybe we need to edit repo settings to remove circleci from required checks.

**Review by alexeagle — APPROVED** [review]
The lost coverage is pretty sad, but this project has no resources to rebuild that on some other infra, and Angular team wants us to stop free-riding on their CircleCI subscription.

**Pull request merged**
