### PR TITLE
feat: add support for Label in nodejs_binary#entry_point

### LINKED ISSUE #32: Support for entry points relative to current BUILD file directory
Currently, users provide the full path to a local js file to use it as an entry point, including the workspace name. It's a bit of extra typing, but it's workable.

This gets a bit more cumbersome for nodejs_binary using entry points that aren't at fixed locations e.g. from other rules in macros. (FWIW this isn't an issue for rules e.g. `ctx.workspace_name + "/" + ctx.file.foo.path`, but it's unrelated because rules can't call other rules.)

Below is an example: we have an intermediary rule which outputs a js file, and we want the nodejs_binary to use it as an entry point. But the macro doesn't know the path to the js file, so we have to get the user to specify the path.

``` python
def foo_rule(
        name,
        # "workspace_name/path/to/BUILD/directory/"
        current_path,
        visibility = None):

    # Intermediary rule outputs "{name}.js".
    intermediary_name = "%s.intermediary" % name
    intermediary_rule(
        name = intermediary_name,
    )

    # Nodejs rule combines current path with known output name
    nodejs_binary(
        name = name,
        data = [
            "@//:node_modules",
            intermediary_name,
        ],
        entry_point = "%s%s.js" % (current_path, intermediary_name),
        visibility = visibility,
    )
```

# Proposal

Add the current path to the node module resolver's list of resolve paths.

The above entry point can be changed to a relative path:

```python
    nodejs_binary(
        # ...
        entry_point = "%s.intermediary.js" % name,
```

## Caveats

Files supplied in `data` would clash with node_modules. Convoluted example:

``` python
    nodejs_binary(
        # ...
        data = [
            "@//:node_modules",
            "some_node_module/foo.js",
        ],
        entry_point = "example.js",
    )
```

```javascript
const foo = require('some_node_module/foo.js'); // Which one?
```

# Alternatives considered

## Change entry_point to be [`attr.label`](https://docs.bazel.build/versions/master/skylark/lib/attr.html#label) instead of attr.string

Ruled out because this would break references to node_modules.

## Split entry_point into two attributes, one attr.label for local references, one attr.string for node_modules references

Not as straightforward for users.

## Split nodejs_binary into two rules, one for local entry points, one for node_modules entry points

Not as straightforward for users.

### PR DESCRIPTION
**Pull request by manekinekko**
Closes #32

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

nodejs_binary#entry_point was a string.

## What is the new behavior?

nodejs_binary#entry_point is now a Label.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

The `entry_point` accepts a target's name as an entry point. If the target is a rule, it should produce the JavaScript entry file that will be passed to the nodejs_binary rule). For example:

 ```
        filegroup(
            name = "entry_file",
            srcs = ["workspace/path/to/entry/file"]
        )
        nodejs_binary(
          name = "my_binary",
          ...
          entry_point = ":entry_file",
        )
```

If the entry JavaScript file belongs to the same package (as the BUILD file), you can simply reference it by its relative name to the package directory:

```
        nodejs_binary(
          name = "my_binary",
          ...
          entry_point = ":file.js",
        )
```

## ⚠️ Downstream Rules That Need To Be Updated ⚠️
- [ ] rules_typescript: https://github.com/sfeir-open-source/rules_typescript/commit/9538466
- [ ] rules_sass: https://github.com/manekinekko/rules_sass/commit/9862dfc

### CODE REVIEW

**Comment by manekinekko** [comment]
Please ignore the failing tests. This PR is in WIP.

**Comment by manekinekko** [comment]
@alexeagle you mentioned that we shouldn't actually use the `expand_path_into_runfiles` helpe and that Bazel has built-in function to get the path for a file. Which function did you have in mind?

**Comment by manekinekko** [comment]
Blocked by https://github.com/bazelbuild/rules_nodejs/pull/691

**Comment by manekinekko** [comment]
Update status:
- `./scripts/test_packages_all.sh`: Green locally
- `./scripts/test_examples_all.sh`: Red locally (because of webpack/src/cli)
- `./scripts/test_legacy_e2e_all.sh`: Green locally
- `./scripts/test_e2e_all.sh`: Red locally (because of firefox)

**Comment by gregmagolan** [comment]
Replaced by #777

**Pull request closed without merging**
