### PR TITLE
feat(vite): initial vite rules package

### PR DESCRIPTION
**Pull request by dymart**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
Currently there are no bazel rules that work with vite. https://vitejs.dev/

## What is the new behavior?
Add bazel rules that work with vite dev server and build 

This is a minimal working set of rules for vite. I wanted to get feedback and suggestions on the implementation. 

Also feedback on the best way to test these rules.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by alexeagle** [comment]
Hi @dymart this is exciting :)

If you'd like a quicker round-trip on communication it might be useful to chat in the `#javascript` channel in slack.bazel.build

We've been thinking of reducing scope here in this repo. As I recently updated on https://bazelbuild.github.io/rules_nodejs/#scope-of-the-project
> We would like to avoid adding more custom rules for specific npm packages.

More of the reasoning is in https://github.com/bazelbuild/rules_nodejs/issues/2892

What do you think about having a rules_vite living on its own, in a repo of your choosing? We recently started a new ruleset
https://github.com/aspect-dev/rules_webpack as you can see it was generated from a GitHub template.

I can still give help over there. It would make many things simpler for you, vs. all the boilerplate required to be a package here. OTOH it means there's no CI coverage for changes to rules_nodejs breaking rules_vite, but we have been very stable so I think it's probably still worth it.

**Comment by dymart** [comment]
Hey @alexeagle, thanks so much for the feedback!! I'll move the rules into their own repo and follow up on slack! Thanks for explaining

**Comment by xvzf** [comment]
@dymart did you proceed on this PR?

**Comment by alexeagle** [comment]
no I don't think there's been any progress on Vite, needs some company to sponsor the work.

**Pull request closed without merging**
