### PR TITLE
feat(examples): add nodejs_binary cluster example

### PR DESCRIPTION
**Pull request by Toxicable**
Adds a basic example of how to use the clustering module in Nestjs.

It currently fails with 
```
Error: Cannot find module 'examples_nestjs/src/app.module'
Require stack:
- /SNIP/execroot/examples_nestjs/bazel-out/darwin-fastbuild/bin/src/server.sh.runfiles/examples_nestjs/src/main.js
```

So also doubles as a test for the linker applying correctly to `nodejs_binary`
When this passes then this should be resolved https://github.com/bazelbuild/rules_nodejs/issues/227

### CODE REVIEW

**Comment by alexeagle** [comment]
You say this currently fails, but the CI is green. What is left to do before merging?

**Comment by Toxicable** [comment]
@alexeagle It fails when I run the program locally, I guess there's no test that actually starts the program up.
I was also working on a parallel PR to add some e2e test for this example.

**Comment by Toxicable** [comment]
Added some testting here https://github.com/bazelbuild/rules_nodejs/pull/1528

**Comment by alexeagle** [comment]
Could you rebase this please?

**Pull request merged**
