### PR TITLE
Remove usage of deprecated Bazel features

### PR DESCRIPTION
**Pull request by jjudd**
This makes rules_nodejs compatible with `--all_incompatible_changes`, best I can tell.

### CODE REVIEW

**Comment by jjudd** [comment]
I was updating our internal version of Bazel to 0.16 and these errors showed up with `--all_incompatible_changes` enabled, so I fixed them.

**Comment by alexeagle** [comment]
could you also add the `--all_incompatible_changes` flag to our repo(s) so we locally catch regressions?

**Comment by pauldraper** [comment]
@jjudd the Circle CI builds are using Bazel 0.14. If you update angular/ngcontainer to 0.5.0, those are using Bazel 0.16.1 and it should work.

(BTW, holy frigging crap, angular/ngcontainer is over 2GB.)

**Comment by alexeagle** [comment]
@pauldraper I would love to make that docker container smaller, I do a few things in there to trim it down (like delete downloads and intermediate output directories) but I struggled to even make a docker container that works. Would love some help there :)

**Comment by pauldraper** [comment]
@alexeagle looks like almost all of that comes from circleci/node:10.9.0-browsers. And a lot that is browsers.

**Comment by alexeagle** [comment]
while we are at it, this change ought to include whatever config change or linter so that it doesn't regress

**Comment by gregmagolan** [comment]
@alexeagle @pauldraper The browsers in ngcontainer aren't needed in many cases now (angular-bazel-example for example) since ts_web_test_suite now uses browsers from rules_webtesting. I think angular/angular may still depend on the browsers being in the docker image for some old tests.

**Comment by alexeagle** [comment]
This got stale, and Bazel team has been sending PRs to flip individual `--incompatible_*` flags so I think we'll just let that process unfold

**Pull request closed without merging**
