### PR TITLE
fix: @npm//foobar:foobar__files target no longer includes nested node_modules

### PR DESCRIPTION
**Pull request by gregmagolan**
The expected behavior would be that @npm//foobar:foobar__files would just be the files in the package and not the nested node_modules that may or may not be there depending on the behavior of the package installer.

Pre-req for https://github.com/angular/angular/pull/33927

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by gregmagolan** [comment]
I thought about that but I think the current `foo__files` filegroup is wrong and anyone using it (which is probably no one) would not expect it to contain the nested node_modules.

**Comment by gregmagolan** [comment]
The `@npm//foo`  depends on `@npm//foo:foo_all_files`  so that rules gets the transitive deps if they are not hoisted. If `foo` has a dep on `bar` and bar is hoisted then `@npm//foo` will also depend on `@npm//bar:bar__contents`.

**Comment by alexeagle** [comment]
do we have to expose both `@npm//foo` and `@npm//foo:foo_all_files`? seems like you're saying users should never reference the latter

**Comment by gregmagolan** [comment]
`@npm//foo:foo__all_files` and `@npm//foo:foo__nested_node_modules` could be private visibility.

`@npm//foo:foo__files` is useful to access the raw filegroup that is the npm package without any nested node_modules.

**Pull request merged**
