### PR TITLE
fix(builtin): don't allow symlinks to escape into duplicate node_modules tree in runfiles

### PR DESCRIPTION
**Pull request by gregmagolan**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by mrmeku** [comment]
@gregmagolan Just wanted to say that I tested out this PR and it was the magic bullet for me to get jest tests working in a react project. Nice work Greg!

**Comment by mrmeku** [comment]
Fixes https://github.com/bazelbuild/rules_nodejs/issues/1447

**Comment by mrmeku** [comment]
@gregmagolan You should consider applying the same fix to NPM package bin. With this fix there is now a mismatch in behavior between `npm_package_bin` and `nodejs_binary`. In the former, node modules can still be resolved from within `npm/modules`. To rectify, I think you can do the following:

Augment [`run_node` ](https://github.com/bazelbuild/rules_nodejs/blob/a096a9e2d291502b83633d10cbe4fda2f414abb1/internal/providers/node_runtime_deps_info.bzl#L70)to include a dictionary of environment variables. 

`{NODE_MODULES_ROOT: _compute_node_modules_root(ctx)}`

**Comment by gregmagolan** [comment]
Good call. Thanks @mrmeku .

**Comment by gregmagolan** [comment]
It's all within the same root but we want to keep node from following symlinks to different node_modules trees as programs will think there are multiple versions of dependencies.

In short,

`/root/repo/node_modules` --- this is where we want resolve to
`/root/npm/node_modules` --- this is where node can end up if it follows symlinks from the above
`/root/repo/external/npm/node_modules` --- alternate legacy runfiles version (not present if --nolegacy_external_runfiles is set)

If we remove node_modules out of runfiles in the future then this is mitigated for `bazel test` although may still be a problem for `run` and `build` which don't have runfiles and just run out of the execroot.

**Comment by alexeagle** [comment]
What happens if we set `/root/repo` as the root directory for the node-patches?

Or, let's explore removing these node_modules from runfiles, maybe there is a convenient way to make that conditional on the target being opted-in to using the node-patches

**Comment by gregmagolan** [comment]
@alexeagle That may actually work for `run` and `test`; we'd still have the legacy external runfiles `/root/external/npm/node_modules` path but those may not be a problem as the `/root/node_modules` should not be symlinks into that tree. For the `build` case `execroot/repo/node_modules` is a symlink to `execroot/repo/external/npm/node_modules` so we may still have to prevent that escape. I'll test this out.

**Comment by mrmeku** [comment]
@alexeagle If you want to remove these node_modules from run files I'd recommend using the strategy I outlined in https://github.com/bazelbuild/rules_nodejs/issues/1489

But for `npm_package_bin` Greg's fix would still be necessary since it doesn't make use of a runfiles directory. Somehow or another you'd still need to blacklist grabbing modules from `external/npm`

**Comment by gregmagolan** [comment]
Tried out moving the root to `execroot/wksp` in #1509. I still think this solution is better even with the bazel specific bits. It could be made generic by adding the concept of blacklisted folders within the root which would be `npm/node_modules` and `repo/external/npm_node_modules`.

Commented here on #1509: https://github.com/bazelbuild/rules_nodejs/pull/1509#issuecomment-569349657.

**Comment by soldair** [comment]
i would accept a generic array of directories as "roots" for the patcher instead of the environment variables. That way they can be passed in in a code layer that has a right to care about them. Thanks for trying in #1509

**Comment by mrmeku** [comment]
Have either of you considered using a white list instead of a black list? Right now rules_nodejs is non-hermetic in cases in which a sandbox is reused since prior commands might add other source files or npm dependencies to the sandbox's file tree. Currently the node patches black list some directories we do not want entry into, but alternatively, the strategy could be to use a whitelist of the manifest of files associated with a particular target.

**Comment by alexeagle** [comment]
Discussed in PR review. We still feel like Bazel is laying out a bad FS (the execroot having the "legacy" layout which was removed from runfiles tree) and the best solution is to make the `--nolegacy_external_runfiles` behavior apply always to node programs, under both the execroot and runfiles root, so that there is no duplicate node_modules tree to worry about. We could do this in the linker step, just fix the directory layout so that we never have code observe node_modules in the wrong place

**Comment by gregmagolan** [comment]
Replaced by #1800

**Pull request closed without merging**
