### PR TITLE
add node_modules replace

### PR DESCRIPTION
**Pull request by thelgevold**
Tweaking the rerooting to handle rxjs/node_modules

This is basically the original code from @mrmeku

@alexeagle

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by alexeagle** [comment]
@mrmeku do we still need this change?

**Comment by mrmeku** [comment]
I need to copy my latest version of this code from my closure_ts_binary PR
from rules typescript. It should be more or less the same, but that should
be the reference for what we merge since that code has been tested with
both an angular and angularjs app

**Comment by alexeagle** [comment]
Okay, please open a new PR with the thing that we should merge.

**Comment by mrmeku** [comment]
Donezo: https://github.com/bazelbuild/rules_nodejs/pull/83

**Pull request closed without merging**
